apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-project
  region: us-east-1

managedNodeGroups:
  - name: expense-project
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
    availabilityZones:
    #- us-east-1f